# Generated by Django 4.2.2 on 2023-09-04 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herramienta', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('categoria', models.CharField(choices=[('EJ1', 'Categoria1'), ('EJ2', 'Categoria2')], default='EJ1', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('IND', 'Indefinido')], default='IND', max_length=3)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('fechaTentativa', models.DateField()),
                ('fechaInicio', models.DateField(null=True)),
                ('fechaFin', models.DateField(null=True)),
                ('empleado', models.ManyToManyField(to='tarea.empleado')),
                ('herramienta', models.ManyToManyField(to='herramienta.herramienta')),
                ('supTarea', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tarea.tarea', verbose_name='Tarea padre')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaGeneracion', models.DateField()),
                ('prioridad', models.CharField(choices=[('URG', 'Urgente'), ('NOR', 'Normal')], default='NOR', max_length=3)),
                ('categoria', models.CharField(choices=[('IND', 'Indefinido')], default='IND', max_length=3)),
                ('estado', models.CharField(choices=[('ESP', 'En Espera'), ('FIN', 'Finalizada'), ('PRO', 'En Progreso')], default='ESP', max_length=3)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tarea.tarea', verbose_name='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario', verbose_name='Id del usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaccion', models.CharField(choices=[('EXT', 'Exelente'), ('BNO', 'Bueno'), ('DFI', 'Deficiente'), ('MLO', 'Malo'), ('IND', 'Indefinido')], default='IND', max_length=3)),
                ('tiempoRespuesta', models.CharField(choices=[('EXT', 'Exelente'), ('BNO', 'Bueno'), ('DFI', 'Deficiente'), ('MLO', 'Malo'), ('IND', 'Indefinido')], default='IND', max_length=3)),
                ('observaciones', models.CharField(max_length=255, null=True)),
                ('ordenServicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tarea.ordenservicio')),
            ],
        ),
    ]
