# Generated by Django 4.2.2 on 2023-09-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0002_tarea_userauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='comentario',
            field=models.CharField(default='No coment', max_length=255),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='descripcion',
            field=models.CharField(default='No description', max_length=255),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='fechaNesesidad',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='sector',
            field=models.CharField(default='No sector', max_length=32),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='fechaGeneracion',
            field=models.DateField(auto_now=True),
        ),
    ]
