# Generated by Django 4.2.2 on 2023-09-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0002_tarea_userauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='comentario',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='fechaNecesidad',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='sector',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
