# Generated by Django 4.2.2 on 2023-09-25 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0003_ordenservicio_comentario_ordenservicio_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenservicio',
            name='comentario',
            field=models.CharField(default='No comment', max_length=255),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='tarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tarea.tarea', verbose_name=''),
        ),
    ]
