"""
Django settings for settings project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*2@_(fi9=&nyg%ghe8=cy7db_ytf0hj1*+%_mfkl%q3$swch=-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost']

ALLOWED_HTTP_METHODS = ['GET', 'POST', 'PUT', 'DELETE']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'corsheaders',
    'coreapi',
    'compra',
    'usuario',
    'tarea',
    'inventario',
    'herramienta'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'settings.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('MARIADB_DATABASE'),
        'USER': os.getenv('MARIADB_USER'),
        'PASSWORD': os.getenv('MARIADB_PASSWORD'),
        'HOST': '127.0.0.1',
        'OPTIONS': {
            'read_default_file': str(BASE_DIR / 'my.cnf'),
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Directorio donde se guardarán los archivos subidos
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL base para acceder a los archivos subidos
MEDIA_URL = '/media/'


CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:5173',
    'http://localhost:5173',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    ]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}
AUTH_USER_MODEL = 'usuario.Usuario'

#CSRF TOKEN and SESSION

CSRF_TRUSTED_ORIGINS = ['http://localhost:5173','http://127.0.0.1:5173']

CSRF_COOKIE_NAME = 'csrftoken'
#CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_COOKIE_HTTPONLY = False # Can not read cookie with javascript
SESSION_COOKIE_SAMESITE = 'strict'
CSRF_COOKIE_SECURE = False # Send cookies by https only  

SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = 'strict'
SESSION_COOKIE_SECURE = False

# PROD ONLY
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SAMESITE = 'None' # Send cookies by https only  
# SESSION_COOKIE_SAMESITE = 'None'
# SESSION_COOKIE_SECURE = True

"""
- same site 'strict'.Pasa el token solo entre dominios del mismo sito. mismo protocolo, mismo dominio
- same site False, no permite que el navegador almacene la cookie porque es inseguro
- same site 'None' requiere que secure=True, solo permite https
- same site 'Lax', Se rechaza almacenar las cookies porque se encuentra en un contexto de dominios crusados
"""
