# Generated by Django 4.2.2 on 2023-09-04 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=32)),
                ('unidadMedida', models.CharField(choices=[('metro', 'metro'), ('litro', 'litro'), ('gramo', 'gramo'), ('contable', 'contable')], default='contable', max_length=16)),
                ('cantidad', models.IntegerField()),
                ('codigo', models.CharField(max_length=16, null=True)),
                ('observaciones', models.CharField(max_length=256, null=True)),
                ('puntoReposicion', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('descripcion', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenRetiro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fechaHora', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.insumo')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tarea.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipoInsumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.tipoinsumo'),
        ),
        migrations.CreateModel(
            name='AjusteStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.CharField(max_length=256)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('accionCantidad', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=1)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.insumo')),
            ],
        ),
    ]
