# Generated by Django 4.2.2 on 2023-09-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_tipoinsumo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='estado',
            field=models.CharField(choices=[('OK', 'OK'), ('Eliminado', 'Eliminado'), ('Suspendido', 'Suspendido')], default='OK', max_length=15),
        ),
    ]
