# Generated by Django 4.2.2 on 2023-09-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_tipoinsumo_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
