# Generated by Django 4.2.2 on 2023-10-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_insumo_estado'),
        ('inventario', '0004_rename_descripcion_insumo_nombre'),
    ]

    operations = [
    ]
