# Generated by Django 4.2.2 on 2023-10-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_merge_20231001_2136'),
        ('inventario', '0006_alter_tipoinsumo_descripcion'),
    ]

    operations = [
    ]
