# Generated by Django 4.2.2 on 2023-09-04 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoInsumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHora', models.DateTimeField(auto_now=True)),
                ('observaciones', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('proveedor', models.CharField(max_length=255)),
                ('total', models.FloatField()),
                ('aprobado', models.BooleanField(default=False)),
                ('pedidoInsumo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compra.pedidoinsumo')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('observacion', models.CharField(max_length=255, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.insumo')),
                ('pedidoInsumo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compra.pedidoinsumo')),
            ],
        ),
    ]
