# Generated by Django 4.2.2 on 2023-09-04 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHerramienta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('descripcion', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=16, null=True)),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('En reparación', 'En reparación'), ('Mal estado', 'Mal estado')], default='OK', max_length=16)),
                ('fechaAlta', models.DateTimeField(auto_now=True)),
                ('observaciones', models.CharField(max_length=255, null=True)),
                ('tipoHerramienta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='herramienta.tipoherramienta')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('En reparación', 'En reparación'), ('Mal estado', 'Mal estado')], default='OK', max_length=16)),
                ('observaciones', models.CharField(max_length=255, null=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='herramienta.herramienta')),
            ],
        ),
    ]
