# Generated by Django 4.2.2 on 2023-09-24 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0003_alter_herramienta_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herramienta',
            old_name='nombre',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='estadoherramienta',
            name='herramienta',
        ),
        migrations.RemoveField(
            model_name='herramienta',
            name='estado',
        ),
        migrations.AddField(
            model_name='herramienta',
            name='estadoHerramienta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='herramienta.estadoherramienta'),
        ),
    ]
