# Generated by Django 4.2.2 on 2023-09-25 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0004_rename_nombre_herramienta_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='estadoHerramienta',
        ),
        migrations.AddField(
            model_name='estadoherramienta',
            name='herramienta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='herramienta.herramienta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herramienta',
            name='estado',
            field=models.CharField(choices=[('OK', 'OK'), ('En reparación', 'En reparación'), ('Mal estado', 'Mal estado')], default='OK', max_length=15),
        ),
    ]
